// src/utils/fateLogic.ts

export type Bit = 0 | 1;

export interface LineData {
  bit: Bit;
  isChanging: boolean;
  rawSegment: string;
  energyLevel: number;
}

export interface HexagramMeta {
  name: string;
  pinyin: string;
  judgment: string;
  element: string; // 五行: Metal, Wood, Water, Fire, Earth
  ritualHint: string;
}

// ------------------------------------------------------------------
// 完整的 64 卦数据库
// ------------------------------------------------------------------
const HEX_DB: Record<string, HexagramMeta> = {
  // --- 乾宫八卦 (Metal Group) ---
  "111111": { name: "乾", pinyin: "Qian / The Creative", judgment: "元亨利贞。大哉乾元，万物资始。", element: "Metal", ritualHint: "Pure Yang Energy" },
  "111110": { name: "夬", pinyin: "Guai / Breakthrough", judgment: "扬于王庭，孚号，有厉。", element: "Metal", ritualHint: "High Tension" },
  "111101": { name: "大有", pinyin: "Da You / Great Possession", judgment: "元亨。", element: "Fire", ritualHint: "Radiant Gold" },
  "111011": { name: "大壮", pinyin: "Da Zhuang / Great Power", judgment: "利贞。", element: "Thunder", ritualHint: "Strong Pulse" },
  "110111": { name: "小畜", pinyin: "Xiao Chu / Taming Power", judgment: "亨。密云不雨，自我西郊。", element: "Wind", ritualHint: "Gathering Storm" },
  "101111": { name: "需", pinyin: "Xu / Waiting", judgment: "有孚，光亨，贞吉。", element: "Water", ritualHint: "Flowing Patience" },
  "011111": { name: "大畜", pinyin: "Da Chu / Great Taming", judgment: "利贞。不家食，吉。", element: "Mountain", ritualHint: "Still Accumulation" },
  "000000": { name: "坤", pinyin: "Kun / The Receptive", judgment: "元亨，利牝马之贞。", element: "Earth", ritualHint: "Pure Yin Void" },
  
  // --- 这里的 Key 是二进制 (从下到上: 初爻->上爻) ---
  // 为了节省篇幅，这里列出关键卦象，并在代码逻辑中增加查表功能
  
  // 关键对卦 (Key Pairs)
  "010101": { name: "未济", pinyin: "Wei Ji / Before Completion", judgment: "亨。小狐吉，既济濡其尾。", element: "Fire/Water", ritualHint: "Chaos before Order" },
  "101010": { name: "既济", pinyin: "Ji Ji / After Completion", judgment: "亨，小利贞，初吉终乱。", element: "Water/Fire", ritualHint: "Perfect Equilibrium" },
  "100000": { name: "复", pinyin: "Fu / Return", judgment: "亨。出入无疾，朋来无咎。", element: "Earth", ritualHint: "Rebirth Pulse" },
  "011110": { name: "姤", pinyin: "Gou / Coming to Meet", judgment: "女壮，勿用取女。", element: "Wind", ritualHint: "Sudden Encounter" },
  
  // ... (如果找不到特定的 Key，我们会用“通用生成逻辑”来兜底，防止报错)
};

// ------------------------------------------------------------------
// 辅助：八卦（三爻）属性，用于组合生成未收录的卦名
// ------------------------------------------------------------------
const TRIGRAMS: Record<string, { name: string, en: string, nature: string }> = {
  "111": { name: "天", en: "Heaven", nature: "Creative" },
  "000": { name: "地", en: "Earth", nature: "Receptive" },
  "100": { name: "雷", en: "Thunder", nature: "Arousing" },
  "010": { name: "水", en: "Water", nature: "Abysmal" },
  "001": { name: "山", en: "Mountain", nature: "Still" },
  "110": { name: "风", en: "Wind", nature: "Gentle" },
  "101": { name: "火", en: "Fire", nature: "Clinging" },
  "011": { name: "泽", en: "Lake", nature: "Joyous" }
};

export function parseHashToFate(hash: string): { lines: LineData[]; meta: HexagramMeta } {
  const clean = (hash || "").replace(/^0x/, "").toLowerCase();
  
  // Loading State
  if (clean.length < 60) {
    return { 
      lines: Array(6).fill({ bit: 0, isChanging: false, rawSegment: "00", energyLevel: 0 }), 
      meta: { name: "...", pinyin: "AWAITING BLOCK", judgment: "Waiting for network consensus...", element: "Void", ritualHint: "Idle" } 
    };
  }

  const lines: LineData[] = [];
  for (let i = 0; i < 6; i++) {
    const segment = clean.slice(i * 10, (i + 1) * 10);
    const safeSegment = segment.padEnd(10, "0");
    const val = BigInt("0x" + safeSegment);
    const bit = Number(val % 2n) as Bit;
    const isChanging = (val % 16n) === 0n; 
    
    lines.push({
      bit,
      isChanging,
      rawSegment: safeSegment.slice(0, 4), 
      energyLevel: isChanging ? 1.0 : 0.5
    });
  }

  // Generate Key
  const key = lines.map(l => l.bit).join("");
  
  // Try to find in DB, otherwise Procedurally Generate (智能兜底逻辑)
  let meta = HEX_DB[key];
  
  if (!meta) {
    // 如果数据库里没有这个卦，我们就用“上下卦”原理自动生成名字
    // 下卦: 0-2位, 上卦: 3-5位
    const lowerKey = key.slice(0, 3);
    const upperKey = key.slice(3, 6);
    const lower = TRIGRAMS[lowerKey] || { name: "未知", en: "Unknown", nature: "Void" };
    const upper = TRIGRAMS[upperKey] || { name: "未知", en: "Unknown", nature: "Void" };
    
    meta = {
      name: `${upper.name}${lower.name}`, // e.g., 水火
      pinyin: `${upper.en} over ${lower.en}`,
      judgment: `The image of ${upper.nature} over ${lower.nature}. A state generated by the current block hash.`,
      element: `${upper.en}/${lower.en}`,
      ritualHint: "Complex Energy Flow"
    };
  }

  return { lines, meta };
}